### ISSUE TITLE
[Feature]: Improve checking emitted events when deploying a contract with koba

### ISSUE THREAD

**Issue by alexfertel** [OpenZeppelin/rust-contracts-stylus#145]
### What is the feature you would like to see?

We currently have to create a filter to check if an event gets emitted during a contract deployment. Once https://github.com/OpenZeppelin/koba/issues/3 is resolved, we should just use the tx receipt instead.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines

**Comment by bidzyyys** [comment]
Should be possible with https://github.com/OpenZeppelin/koba/pull/9
