### ISSUE TITLE
[Refactor]: apply same naming convention for all tests that check errors 

### ISSUE THREAD

**Issue by bidzyyys** [OpenZeppelin/rust-contracts-stylus#155]
### What is the feature you would like to see?

We should apply the same naming convention for all tests that check errors:
`fn error_when_<function>_<description>(...)`

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines

**Comment by postmeback** [comment]
I would like to give it a try.

**Comment by alexfertel** [comment]
Sure, go for it! @postmeback

**Comment by postmeback** [comment]
Can you help with a filename, from where I can get started? @alexfertel

**Comment by alexfertel** [comment]
Sure, you can start [here](https://github.com/OpenZeppelin/rust-contracts-stylus/blob/f660b75860ca2f3d2439e41bf78438181ceb7622/contracts/src/token/erc721/mod.rs#L1112).

**Comment by alexfertel** [comment]
We have decided that the trade-off is not worth it, and it's preferable to surface the intent as clearly as possible in test names. As such, I'll be closing this issue as not planned.

**Comment by postmeback** [comment]
Ok  😞

**Comment by alexfertel** [comment]
Hey @postmeback ! I wrote the reasoning in a [comment](https://github.com/OpenZeppelin/rust-contracts-stylus/pull/161#issuecomment-2206717358) on your PR. I really hope this doesn't deter you from contributing. It was our mistake and not yours!
