### ISSUE TITLE
[Feature]: Have debug implementation conditional for erros in tests

### ISSUE THREAD

**Issue by qalisander** [OpenZeppelin/rust-contracts-stylus#165]
Currently all errors types in project has default debug implementation that is necessary just for testing purposes.
Basically it will generate code associated with displaying error that won't be used in release and increase WASM binary size.
We should optimize it and implement `#[derive(Debug)]` just for tests.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines

**Comment by kaustubh1106** [comment]
I want to work on this issue..can you please assign me

**Comment by qalisander** [comment]
Well. You're welcome!

**Comment by kaustubh1106** [comment]
thanks, I am new to the repository and have a few conrtributions before can you help where should I start??

**Comment by qalisander** [comment]
Sure. It is straightforward. You can see there is an optional cfg [attribute](https://github.com/OpenZeppelin/rust-contracts-stylus/blob/02d26d4a1e9b6b7969e73a4ce37fb421de5b45e7/contracts/src/token/erc20/mod.rs#L96) that enables `DefaultStorageMacro`. I think same way we can opt out all `#[Debug]` attributes for errors like [this](https://github.com/OpenZeppelin/rust-contracts-stylus/blob/02d26d4a1e9b6b7969e73a4ce37fb421de5b45e7/contracts/src/token/erc20/mod.rs#L37C5-L37C21).

**Comment by kaustubh1106** [comment]
@qalisander if I am not wrong I have to implement debug trait for mod test in contract/src ? please correct me if I am wrong

**Comment by qalisander** [comment]
Yep. For every error there. You can search by `#[derive(Debug)]` in project to see where it will make sense to make it conditional

**Comment by kaustubh1106** [comment]
sure! thanks for the help sir!

**Comment by kaustubh1106** [comment]
@qalisander please review my PR
