### ISSUE TITLE
EIP712

### ISSUE THREAD

**Issue by bidzyyys** [OpenZeppelin/rust-contracts-stylus#184]
Implement `EIP712` contract. Solidity reference [here](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/cryptography/EIP712.sol).

**Comment by developeruche** [comment]
I want to take on this!

**Comment by bidzyyys** [comment]
Hi @developeruche, we are super happy you want to take this issue and go for it 🚀
As we are working on the ERC-20 Permit (#43), this issue is a high priority right now, so any time you need any help do not hesitate to ask. It also may occur that someone from our team will cooperate with you to get it done quickly.

**Comment by developeruche** [comment]
lovely... on it, and would communicate promptly!
