### ISSUE TITLE
[Docs]: Update Guidelines

### ISSUE THREAD

**Issue by bidzyyys** [OpenZeppelin/rust-contracts-stylus#189]
### What happened?

Project guidelines (e.g. unit tests, E2E tests, benches) should be updated.

Cause: https://github.com/OpenZeppelin/rust-contracts-stylus/pull/187#issuecomment-2211783019

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines

**Comment by ggonzalez94** [comment]
Is this still relevant?
