### ISSUE TITLE
[Bug] Fix syntax highlighting for rust code in docs

### ISSUE THREAD

**Issue by alexfertel** [OpenZeppelin/rust-contracts-stylus#217]
We'd like to have syntax highlighting in our docs dor Rust snippets.

![Screenshot 2024-07-25 at 13 29 33](https://github.com/user-attachments/assets/0e990bff-0aee-4bf1-aef9-424afcd74bd3)

**Comment by ggonzalez94** [comment]
Looks like this has already been fixed. I'll close the issue.
