### ISSUE TITLE
[Feature]: ERC1155

### ISSUE THREAD

**Issue by ggonzalez94** [OpenZeppelin/rust-contracts-stylus#261]
### What is the feature you would like to see?

Implement `ERC1155` standard for Stylus.
Solidity reference implementation [here](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC1155/ERC1155.sol)

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines

**Comment by programskillforverification** [comment]
I want to work on this one, please assign to me

**Comment by bidzyyys** [comment]
Hey @programskillforverification thank you for your eagerness to contribute to our library. You can work on this issue, please update us with any concern/trouble that you need to face.

**Comment by ggonzalez94** [comment]
@programskillforverification thanks for wanting to contribute to the library ❤️ - would be great if you can submit a draft PR with your initial design/implementation, that way our team can give you feedback early on.
