### ISSUE TITLE
[Feature]: SafeERC20 utility

### ISSUE THREAD

**Issue by ggonzalez94** [OpenZeppelin/rust-contracts-stylus#279]
### What is the feature you would like to see?

Wrappers around ERC-20 operations that throw on failure.
Reference implementation: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/utils/SafeERC20.sol

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines

**Comment by vking45** [comment]
I would like to take up this issue

**Comment by bidzyyys** [comment]
@vking45 thanks for wanting to contribute to the library 🚀 Of course you can work on this issue!  
It would be great if you can submit a draft PR with your initial design/implementation, that way our team can give you feedback early on.

**Comment by 0xNeshi** [comment]
@bidzyyys created a [draft PR](https://github.com/OpenZeppelin/rust-contracts-stylus/pull/289) with just `safe_transfer` implemented to show what is the idea for the utility's design, let me know if you have any feedback and I you think I can continue working on this
