### ISSUE TITLE
[Audit]: N-01 Unaddressed TODOs and FIXMEs 

### ISSUE THREAD

**Issue by ggonzalez94** [OpenZeppelin/rust-contracts-stylus#315]
### What is the feature you would like to see?

Throughout the codebase, multiple instances of TODO and FIXME comments were identified:
 - line59 of ERC-20 extension metadata.rs
- line73 of ERC-20 extension enumerable.rs
- line11 of ERC-721 extension enumerable.rs
- line71 of ERC-721 extension mod.rs
 - line486 of ERC-721 extension mod.rs
 - line665 of ERC-721 extension mod.rs
 
 During development, having well-described TODO or FIXME comments will make the process of tracking and resolving them easier. Without this information, these comments might age and important information for the security of the system might be forgotten by the time it is released to production. As such, consider removing all instances of TODO or FIXME comments and instead tracking them in the issues backlog. Alternatively, consider linking each inline TODO or FIXME to a corresponding backlog issue.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines

**Comment by bidzyyys** [comment]
Closed by https://github.com/OpenZeppelin/rust-contracts-stylus/pull/330
