### ISSUE TITLE
[Audit]: N-03 Inconsistent Error Types

### ISSUE THREAD

**Issue by ggonzalez94** [OpenZeppelin/rust-contracts-stylus#316]
### What is the feature you would like to see?

Throughout the codebase, there are some extensions that use associated error types to allow users the flexibility to assign a generic Vec as an error type and encode any error that is needed (or not return an error at all), while others do not use this error style. For example, in the IERC20 trait of the ERC20 implementation.
Consider using a consistent error style to avoid confusion and improve code clarity.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines

**Comment by bidzyyys** [comment]
Moving to next release (`v0.2.0`).

**Comment by bidzyyys** [comment]
Closing as duplication of https://github.com/OpenZeppelin/rust-contracts-stylus/issues/336
