### ISSUE TITLE
[Audit]: M-01 ERC-721 Does Not Support ERC-165 

### ISSUE THREAD

**Issue by ggonzalez94** [OpenZeppelin/rust-contracts-stylus#319]
### What is the feature you would like to see?

The ERC721 implementation does not support ERC-165, which is required by the interface, and popular marketplaces such as OpenSea and Rarible call supportsInterface on any NFTs they interact with. If an ERC-721 implementation does not implement ERC-165, other contracts, dApps, or marketplaces will not be able to easily verify whether the contract supports the ERC-721 interface. This means that platforms or third parties that rely on ERC-165 to check for compliance will not recognize the contract as an ERC-721 token. As a result, the NFT contract may face limited interoperability and integration issues with external systems that expect proper ERC-165 implementation.
Consider adding support for ERC-165 to ensure compatibility with marketplaces and third- party systems.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines

**Comment by bidzyyys** [comment]
Closed by https://github.com/OpenZeppelin/rust-contracts-stylus/pull/309
