### ISSUE TITLE
Add support interface ERC165 to our contracts

### ISSUE THREAD

**Issue by qalisander** [OpenZeppelin/rust-contracts-stylus#33]
### What is the feature you would like to see?

Implement a function selector that is same as [ERC165](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/cb2aaaa04a292887c49839cd958b08a83979d746/contracts/utils/introspection/ERC165.sol#L20) for solidity.

Also think about ways to to retrieve function selectors and interface id (that is basically xor of all function selectors in the interface).
Would be great to have a convenient function selector support from stylus sdk as it is at solidity.

Helpful links:
- function_selector! [macro](https://github.com/OffchainLabs/stylus-sdk-rs/blob/290326c9f28057f20cbe881738b913ed34c20755/stylus-sdk/src/abi/mod.rs#L78).
- function [selectors](https://docs.rs/alloy-sol-types/latest/alloy_sol_types/trait.SolInterface.html#method.selectors) in the alloy crates.

Add the standard to the following contracts:
- [ ] ERC721URIStorage (#56)
- [ ] ERC721 (#28)
- [ ] ERC721Enumerable (#67)

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines

**Comment by ggonzalez94** [comment]
Moving this to milestone 2 since it is not a major priority and we are focusing in docs + upgrading the sdk version.
