### ISSUE TITLE
[Feature]: ERC1155 Supply Extension 

### ISSUE THREAD

**Issue by qalisander** [OpenZeppelin/rust-contracts-stylus#350]
### What is the feature you would like to see?

Add ERC1155 supply extension ([solidity](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/dbb6104ce834628e473d2173bbc9d47f81a9eec3/contracts/token/ERC1155/extensions/ERC1155Supply.sol#L21))

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines

**Comment by bidzyyys** [comment]
Blocked by #261

**Comment by bidzyyys** [comment]
Bringing back @programskillforverification code.
