### ISSUE TITLE
[Feature]: ERC1155 URIStorage Extension

### ISSUE THREAD

**Issue by qalisander** [OpenZeppelin/rust-contracts-stylus#351]
### What is the feature you would like to see?

Add ERC1155 URIStorage extension ([solidity](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/dbb6104ce834628e473d2173bbc9d47f81a9eec3/contracts/token/ERC1155/extensions/ERC1155URIStorage.sol#L13))

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines

**Comment by bidzyyys** [comment]
Blocked by #261

**Comment by bidzyyys** [comment]
Bring back @programskillforverification code -> https://github.com/OpenZeppelin/rust-contracts-stylus/pull/275/commits/dd932cd7e2ec68003b2681cb195b6dde0fdaf72f
