### ISSUE TITLE
[Bug]: Impossible to deploy contract on the latest nightly

### ISSUE THREAD

**Issue by qalisander** [OpenZeppelin/rust-contracts-stylus#374]
### What happened?

Currently nightly versions higher then `nightly-2024-07-25` doesn't work.

![image](https://github.com/user-attachments/assets/88844f7d-ca64-4fab-83c4-b71ec4f196cc)

### platform

- [X] linux
- [ ] windows
- [X] macos

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines

**Comment by ggonzalez94** [comment]
This seems to be an issue with `cargo stylus check` itself. Since the same error happens on a brand new stylus project without even including the library as a dependency
