### ISSUE TITLE
[Feature]: Turn All `Call::new_in` into `Call::new` (i.e. Stop Supporting Reentrancy)

### ISSUE THREAD

**Issue by 0xNeshi** [OpenZeppelin/rust-contracts-stylus#434]
### What is the feature you would like to see?

[Slack discussion](https://openzeppelin.slack.com/archives/C06R5AGFE9G/p1732632475656059).
In short, the team agreed we would not be supporting reentrant patterns.

Doing this will enable us to remove `TopLevelStorage` impls from most, if not all contracts.

TODO:

- [ ] Turn all `Call::new_in` into `Call::new` calls (wherever applicable).
- [ ] Update all functions that were `&mut self` only because of using `Call::new_in` to now be just `&self`.
- [ ] Remove `TopLevelStorage` impls wherever possible.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines

**Comment by SarveshLimaye** [comment]
Hey @0xNeshi , Can I work on this issue?

**Comment by 0xNeshi** [comment]
Hi @SarveshLimaye , you're more than welcome to work on this!
