### ISSUE TITLE
Move motsu to its own repo

### ISSUE THREAD

**Issue by ggonzalez94** [OpenZeppelin/rust-contracts-stylus#455]
### What is the feature you would like to see?

It's easier for external contributions and keeping things more organized if we move motsu to a new `stylus-test-helpers` repository and publish the crate from there.
We might eventually do the same for `e2e` if there's enough demand.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines

**Comment by Ifechukwudaniel** [comment]
i have been praying for this
